version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/src/infra"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/src/infra/sample-apis/basic-api"
    schedule:
      interval: "daily"
