displayName: 1000 Bytes - <Sub-System>
testPlan: quick_test.jmx
description: APIM 1000 Bytes Baseline Test
engineInstances: 2
testId: 1000bytes<Sub-System>
testType: JMX
splitAllCSVs: False
failureCriteria: []
env:
- name: domain
  value: <API Url>
- name: protocol
  value: https
- name: throughput_per_engine
  value: 250
- name: max_response_time
  value: 500
- name: ramp_up_time
  value: 60
- name: duration_in_sec
  value: 300
- name: path
  value: bytes/1000
autoStop:
  errorPercentage: 90
  timeWindow: 60
