# This workflow runs on the subsmission of Pull Request. It validates and formats the Terraform code in the merging branch. 
# If Terraform identifies formatting changes, it will commit the changes back to the branch.

name: Build - Validate and format Terraform 

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    
permissions:
      id-token: write
      contents: read
env:
  TerraformWorkingDirectory: "./src/infra"
  StateStoreRGName: ${{ vars.STATE_STORE_RGNAME }}
  StorageAccountName: ${{ vars.STORAGE_ACCOUNT_NAME }}
  StateStoreContainerName: ${{ vars.STATE_STORAGE_CONTAINER_NAME }}
  StateStoreFilename: "self-hosted-gateway.tfstate"

jobs:
  Validate-and-Format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}


      - uses: hashicorp/setup-terraform@v3
        name: Setup Terraform
        
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Terraform Init
        run: terraform init -backend-config=resource_group_name=${{ env.StateStoreRGName}} -backend-config=storage_account_name=${{ env.StorageAccountName }} -backend-config=container_name=${{ env.StateStoreContainerName }} -backend-config=key=${{ env.StateStoreFilename }}
        working-directory: ${{ env.TerraformWorkingDirectory }}
        env:
             ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
             ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID  }}
             ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
             ARM_USE_OIDC: true

      - name: Validate Terraform
        run: terraform validate
        working-directory: ${{ env.TerraformWorkingDirectory }}
        env:
             ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
             ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID  }}
             ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
             ARM_USE_OIDC: true
        
      - name: Format Terraform
        id: fmt
        run: | 
          terraform fmt -recursive -write=true
          firstLine=`echo "$(git status -s *.tf)" | head -1`
          echo "format_output=$firstLine" >> $GITHUB_OUTPUT

      - name: Commit format changes to branch
        if: ${{ steps.fmt.outputs.format_output != '' }}
        run: | 
          GIT_BRANCH=$(echo ${GITHUB_HEAD_REF})
          git remote set-url origin "https://${{github.actor}}:${{github.token}}@github.com/${{ github.repository }}"
          git config user.name "GitHub Actions"
          git config user.email ""
          git add .
          git commit -m "chore: Format Terraform"
          git push origin $GIT_BRANCH
        
